all:
    hosts:
            host1:
                      ansible_host: localhost
                      ansible_connection: local
                      ansible_user: root
                      become_user: root
                      ansible_password: tpstps
                      ansible_become_pass: tpstps
#                      installDir: /root/
                      postgres_user: ansible
                      postgres_user_password: tpstps
                      postgres_database: deploymenthub
    #                  frontend_path_default: /var/www/html
                      frontend_path: /home/ansible/deployment_hub
                      backend_IP: 192.168.4.245
                      backend_Port: 3333
                      backend_path: /home/ansible/deployment_hub
                      server_root_path: /home/ansible/deployment_hub/ansibleBackend
                      backup_base_folder_path: /home/ansible/.bk
                      base_artifacts_folder: /home/ansible/artifacts
                      postgres_host: 192.168.4.245
                      postgres_port: 5432
                      protocol: http
